# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Amarendra Sharma
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: ' I am an  web developer with more than 1 years of well-rounded experience. My skills include Angular Js, Laravel development, and graphic design.
I also have experience with SEO and online advertising. <a href="#" target="_blank">resume/CV template here</a>.'

#sidebar links
email: s.amarendra1995@gmail.com
phone: 961 340 8174
#website: blog.webjeda.com 
linkedin: amarendra-sharma
github: amarendrasharma
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

theme: jekyll-theme-cayman